# Generated by Django 6.0.7 on 2026-07-16 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_department_user_faculty_user_level_and_more'),
        ('elections', '0006_election_register'),
        ('system', '0003_institution_ec_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='system.institutionprofile'),
        ),
        migrations.CreateModel(
            name='ECUnit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('main', 'Main EC'), ('sub', 'Sub EC')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_units', to='system.institutionprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.ecunit')),
            ],
            options={
                'ordering': ['unit_type', 'name'],
                'unique_together': {('institution', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ECMembership',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('chair', 'Chair'), ('member', 'Member'), ('registrar', 'Registrar')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_memberships', to=settings.AUTH_USER_MODEL)),
                ('ec_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.ecunit')),
            ],
            options={
                'ordering': ['ec_unit__name', 'user__email'],
                'unique_together': {('user', 'ec_unit')},
            },
        ),
        migrations.CreateModel(
            name='SubECAssignment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ec_assignments', to='elections.department')),
                ('ec_unit', models.ForeignKey(limit_choices_to={'unit_type': 'sub'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.ecunit')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ec_assignments', to='elections.faculty')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('faculty__isnull', False), ('department__isnull', False), _connector='OR'), name='sub_ec_assignment_has_scope')],
            },
        ),
    ]
