# Generated by Django 6.0.7 on 2026-07-16 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_institution_ec_hierarchy'),
        ('system', '0003_institution_ec_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainECDecision',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(choices=[('election_create', 'Create election'), ('election_update', 'Update election'), ('election_open', 'Open election'), ('election_close', 'Close election'), ('election_delete', 'Delete election')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('result_ref', models.CharField(blank=True, max_length=64)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ec_decisions', to='system.institutionprofile')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_ec_decisions', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_ec_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainECDecisionApproval',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='accounts.mainecdecision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_decision_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('decision', 'user')},
            },
        ),
    ]
