# Generated by Django 6.0.7 on 2026-07-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_main_ec_dual_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainecdecision',
            name='decision_type',
            field=models.CharField(choices=[('election_create', 'Create election'), ('election_update', 'Update election'), ('election_open', 'Open election'), ('election_close', 'Close election'), ('election_delete', 'Delete election'), ('sub_ec_create', 'Create Sub EC')], max_length=40),
        ),
    ]
