# Generated by Django 6.0.7 on 2026-07-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_level_and_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainecdecision',
            name='decision_type',
            field=models.CharField(choices=[('election_create', 'Create election'), ('election_update', 'Update election'), ('election_open', 'Open election'), ('election_close', 'Close election'), ('election_delete', 'Delete election'), ('sub_ec_create', 'Create Sub EC'), ('register_create', 'Create voter register')], max_length=40),
        ),
    ]
