# Generated by Django 6.0.7 on 2026-07-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_register_replace_staging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainecdecision',
            name='decision_type',
            field=models.CharField(choices=[('election_create', 'Create election'), ('election_update', 'Update election'), ('election_open', 'Open election'), ('election_close', 'Close election'), ('election_delete', 'Delete election'), ('sub_ec_create', 'Create Sub EC'), ('sub_ec_update', 'Update Sub EC'), ('register_create', 'Create voter register'), ('register_replace', 'Replace voter register'), ('register_entry_update', 'Update voter register entry')], max_length=40),
        ),
    ]
