# Generated by Django 6.0.7 on 2026-07-15 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_department_faculty_level_election_scope_type_and_more'),
        ('ussd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='provider_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('error', 'Error')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='USSDVoterPin',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_pins', to='elections.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('election', 'user')},
            },
        ),
    ]
