# Generated by Django 6.0.7 on 2026-07-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0003_department_faculty_level_election_scope_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='academic_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='elections.department'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='elections.faculty'),
        ),
    ]
