# Generated by Django 6.0.7 on 2026-07-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_faculty_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='academic_department',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='department',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='faculty',
        ),
    ]
