# Generated by Django 6.0.7 on 2026-07-08 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0002_votingchannel'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreVotePresenceCapture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='web', max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pre_vote_presence/%Y/%m/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.election')),
                ('svt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='security.svttoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'election', 'svt')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_hash', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidates.candidate')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.votingchannel')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.position')),
                ('svt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='security.svttoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'position', 'candidate')},
            },
        ),
    ]
