# Generated by Django 6.0.7 on 2026-07-11 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancestate',
            name='uuid',
        ),
        migrations.AddField(
            model_name='featureflag',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='maintenancestate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution/'),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='name',
            field=models.CharField(default='VoterB', max_length=255),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='short_name',
            field=models.CharField(default='VoterB', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancestate',
            name='message',
            field=models.TextField(blank=True, default='The system is currently under maintenance. Please check back later.'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('integrations', 'Integrations'), ('governance', 'Governance'), ('operations', 'Operations')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SettingRevision',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
