# Generated by Django 6.0.7 on 2026-07-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_maintenancestate_uuid_featureflag_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionprofile',
            options={'ordering': ['name'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
