# Generated by Django 6.0.7 on 2026-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='presence_capture_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
