# Generated by Django 6.0.7 on 2026-07-17 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_election_owner_ec_scope'),
        ('security', '0002_auditlog_presence_capture_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SVTAbuseBlock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default='foreign_svt_attempt', max_length=80)),
                ('blocked_until', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='svttoken',
            index=models.Index(fields=['user', 'election', 'status'], name='security_sv_user_id_38d38b_idx'),
        ),
        migrations.AddIndex(
            model_name='svttoken',
            index=models.Index(fields=['election', 'token_hash'], name='security_sv_electio_222513_idx'),
        ),
        migrations.AddField(
            model_name='svtabuseblock',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svt_abuse_blocks', to='elections.election'),
        ),
        migrations.AddField(
            model_name='svtabuseblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svt_abuse_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='svtabuseblock',
            index=models.Index(fields=['user', 'election', 'blocked_until'], name='security_sv_user_id_d90fd8_idx'),
        ),
    ]
