# Generated by Django 6.0.7 on 2026-07-16 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_department_faculty_level_election_scope_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='election_type',
        ),
        migrations.RemoveField(
            model_name='election',
            name='scope_department',
        ),
        migrations.RemoveField(
            model_name='election',
            name='scope_faculty',
        ),
        migrations.RemoveField(
            model_name='election',
            name='scope_level',
        ),
        migrations.RemoveField(
            model_name='election',
            name='scope_type',
        ),
        migrations.CreateModel(
            name='VoterRegister',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='elections.election')),
            ],
            options={
                'unique_together': {('election', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VoterCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='elections.voterregister')),
            ],
            options={
                'verbose_name_plural': 'voter categories',
                'unique_together': {('register', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VoterRegisterImport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter_register_imports', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='elections.voterregister')),
            ],
        ),
        migrations.CreateModel(
            name='VoterRegisterEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='elections.votercategory')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='elections.voterregister')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'voter register entries',
                'unique_together': {('register', 'voter_id')},
            },
        ),
    ]
