# Generated by Django 6.0.7 on 2026-07-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_remove_election_scope_type_add_voter_registers'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='allow_all_voters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='restricted_categories',
            field=models.ManyToManyField(blank=True, related_name='restricted_positions', to='elections.votercategory'),
        ),
    ]
