# Generated by Django 6.0.7 on 2026-07-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_position_category_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_elections', to='elections.voterregister'),
        ),
    ]
