# Generated by Django 6.0.7 on 2026-07-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_institutional_registers'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregister',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='voterregister',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
