# Generated by Django 6.0.7 on 2026-07-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_voterregister_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregisterentry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
