# Generated by Django 6.0.7 on 2026-07-17 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_mainecdecision_decision_type'),
        ('elections', '0010_voterregisterentry_phone_number'),
        ('system', '0003_institution_ec_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='system.institutionprofile'),
        ),
        migrations.AddField(
            model_name='election',
            name='owner_ec_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_elections', to='accounts.ecunit'),
        ),
        migrations.AddField(
            model_name='election',
            name='owner_type',
            field=models.CharField(choices=[('main', 'Main EC (institutional)'), ('sub', 'Sub EC (category)')], db_index=True, default='main', max_length=10),
        ),
    ]
