# Generated by Django 6.0.7 on 2026-07-17 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_election_owner_ec_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterregister',
            name='replace_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_replacements', to='elections.voterregister'),
        ),
    ]
