# Generated by Django 6.0.7 on 2026-07-17 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_register_replace_staging'),
        ('strongroom', '0003_vault_access_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCastEvidence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_code_hash', models.CharField(db_index=True, max_length=128)),
                ('channel', models.CharField(default='web', max_length=20)),
                ('audit_log_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('presence_capture_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('device_log_id', models.UUIDField(blank=True, null=True)),
                ('location_log_id', models.UUIDField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('browser_fingerprint', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('presence_image_path', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ballot_seal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_evidence', to='strongroom.ballotseal')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_cast_evidence', to='elections.election')),
            ],
            options={
                'indexes': [models.Index(fields=['election', 'created_at'], name='strongroom__electio_a7a602_idx'), models.Index(fields=['election', 'confirmation_code_hash'], name='strongroom__electio_19bd5f_idx')],
            },
        ),
    ]
