# Generated by Django 6.0.7 on 2026-07-17 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_institutioncategory'),
        ('strongroom', '0004_vote_cast_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strongroomcommittee',
            name='nominee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='strongroomcommittee',
            name='nominee_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strongroomcommittee',
            name='nominee_key_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strongroomcommittee',
            name='nominee_key_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='strongroomcommittee',
            name='nominee_key_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strongroomcommittee',
            name='nominee_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='strongroomcommittee',
            name='peer_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strongroomcommittee',
            name='peer_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strongroomcommittee',
            name='peer_ec',
            field=models.ForeignKey(blank=True, help_text='Second EC who must approve this custody committee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strongroomcommitteemember',
            name='role',
            field=models.CharField(choices=[('chair', 'Chair'), ('custodian', 'Custodian'), ('observer', 'Observer'), ('main_ec', 'Main EC'), ('peer_ec', 'Peer EC'), ('nominee', 'Candidate Nominee')], default='custodian', max_length=20),
        ),
        migrations.CreateModel(
            name='VaultUnlockChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('awaiting_peer', 'Awaiting peer EC'), ('awaiting_nominee', 'Awaiting nominee key'), ('open', 'Open'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='awaiting_peer', max_length=20)),
                ('peer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('nominee_verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock_challenges', to='strongroom.strongroomaccesssession')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_challenges', to='strongroom.strongroomcommittee')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_unlock_challenges', to='elections.election')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_unlocks_started', to=settings.AUTH_USER_MODEL)),
                ('peer_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_unlocks_confirmed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='strongroom__status_eeba0b_idx'), models.Index(fields=['committee', 'status'], name='strongroom__committ_0010c1_idx')],
            },
        ),
    ]
